In [7]:
import numpy as np
import pandas as pd
df = pd.read_csv('simulation_data.csv')
df = df[df['frame'] == 0]

In [8]:
R_EQ = 4

In [9]:
import pandas as pd
import numpy as np

# Supposons que votre tableau est déjà chargé dans un DataFrame pandas
# df = pd.read_csv('votre_fichier.csv')  # Si vous lisez à partir d'un fichier CSV

# Extraire les colonnes x et y
points = df[['x', 'y']].values

# Initialiser une liste pour stocker les paires de points et leurs distances
paires_proches = []

# Calculer les distances et filtrer celles inférieures à 8
n = len(points)
for i in range(n):
    for j in range(i + 1, n):  # On évite de comparer un point avec lui-même et les doublons (i < j)
        distance = np.sqrt((points[i, 0] - points[j, 0])**2 + (points[i, 1] - points[j, 1])**2)
        if distance < 8:
            paires_proches.append({
                'particle_1': df.loc[i, 'particle'],
                'particle_2': df.loc[j, 'particle'],
                'distance': distance
            })

# Convertir la liste en DataFrame pour une meilleure lisibilité
paires_proches_df = pd.DataFrame(paires_proches)

paires_proches_df

   particle_1  particle_2  distance
0           7          13  5.900364
1           8          18  2.382215

In [10]:
indices_a_supprimer = []

# Ici, on parcourt les indices du DataFrame (attention, on suppose que les indices sont consécutifs)
for i in range(len(paires_proches_df)):
    if paires_proches_df.loc[i, 'particle_1'] == paires_proches_df.loc[i, 'particle_2']:
        indices_a_supprimer.append(i)

# Supprimez ensuite toutes les lignes repérées
paires_proches_df.drop(index=indices_a_supprimer, inplace=True)
# Si besoin, réindexez le DataFrame
paires_proches_df.reset_index(drop=True, inplace=True)

In [11]:
paires_proches_df

   particle_1  particle_2  distance
0           7          13  5.900364
1           8          18  2.382215